language: ruby

rvm:
  - 2.3.1
  - 2.4.2
  - 2.5.3

# script, expressed as an array, is necessary for 'bundle exec coveralls push' to work locally
script:
  - bundle exec rake

cache: bundler

notifications:
  email: false
